/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ioc.demo;
import org.springframework.cglib.proxy.Enhancer;
import org.springframework.cglib.proxy.MethodInterceptor;
import org.springframework.cglib.proxy.MethodProxy;

import java.io.IOException;
import java.io.OutputStream;
import java.lang.reflect.Method;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.LinkedList;
import java.util.List;

public class AppTest {
    public static class Template{

    }

    public static void main(String[] args) throws  Exception {
        ServerSocket serverSocket = new ServerSocket(8080);
        while (true){
            Socket socket = serverSocket.accept();
            new Thread(()->{
                try (OutputStream outputStream = socket.getOutputStream()){
                    outputStream.write("Hello World".getBytes());
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }).start();
        }
    }
}
