/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proxy;

import proxy.cblibproxy.CglibProxy;
import proxy.javaproxy.JProxyFactory;

import java.lang.reflect.Proxy;

public class ProxyApp {


    public static void main(String[] args) {
        //Human h = (Human) Proxy.newProxyInstance(ProxyApp.class.getClassLoader(), new Class[] {Human.class}, new JProxyFactory(new Teacher()));

        Human h = (Human) new CglibProxy(new Teacher()).build();

        h.say("Hello world");
        h.walk();
    }
}
