spring:
  profiles:
    active: 'prod'
  application:
    name: tname
  datasource:
    url: 'jdbc:mysql://94hry.tech:3306/test'
    username: 'test'
    password: 'test'
server:
  servlet:
    context-parameters:
      scp: 'scpV'
logging:
  level:
    org.springframework.boot:
      trace
app:
  meta:
    version: 1
    sub-version: 1