/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package messagequeue;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.jms.annotation.EnableJms;
import org.springframework.jms.annotation.JmsListener;

@SpringBootApplication
@EnableJms
@Slf4j
public class MessageQueueApp implements CommandLineRunner {

    @Autowired
    private MessageProducer producer;

    public static void main(String[] args) {
        SpringApplication.run(MessageQueueApp.class);
    }

    @JmsListener(destination = "testPool")
    public void receive(MessageBean bean) {
        log.info("Receive {}", bean);
    }

    @JmsListener(destination = "ActiveMQ.DLQ")
    public void receiveDeadLetter(MessageBean bean) {
        log.info("Receive dead letter {}", bean);
    }

    @Override
    public void run(String... args) throws Exception {
        producer.produce();
    }
}
