/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package configserver.demo;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.Banner;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.config.server.EnableConfigServer;

@SpringBootApplication
@EnableConfigServer
@Slf4j
public class SpringCloudConfigServer implements CommandLineRunner {

    public static void main(String[] args) {
        SpringApplication application = new SpringApplication(SpringCloudConfigServer.class);
        application.setBannerMode(Banner.Mode.CONSOLE);
        application.run(args);
    }

    @Override
    public void run(String... args) throws Exception {

    }
}
