/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mvc;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
public class MvcApp extends SpringBootServletInitializer {

    public static void main(String[] args) {
        SpringApplication.run(MvcApp.class, args);
    }

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder builder) {
        return builder.sources(MvcApp.class);
    }

    @RestController
    static class VC {

        @GetMapping("index")
        public String index() {
            return "Hello world";
        }
    }
}
