/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zookeeper;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ZookeeperApp {

    public static void main(String[] args) {
        SpringApplication.run(ZookeeperApp.class);
    }
}
