/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package centerangle;

import javax.swing.*;
import java.awt.*;

public class App {
    public static void main(String[] args) {
        JFrame frame = new JFrame("Angle");
        frame.setSize(700, 700);
        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
        JPanel panel = new JPanel() {
            public void paint(Graphics g) {
                super.paint(g);
                CircleCentralAngle angle = new CircleCentralAngle((Graphics2D) g, 250);
                angle.setX(350);
                angle.setY(350);
                angle.paintCircle(Color.red);
                angle.paintCenterPoint(Color.black, 5);
                angle.paintBaseLine(Color.orange, 200, 90, "90");
                angle.paintRelativeLine(Color.green, 100, 60, "150");
            }
        };
        frame.setContentPane(panel);
    }
}
