spring:
  kafka:
    bootstrap-servers: 94hry.tech:9092
server:
  address: 127.0.0.1
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
test:
  test-info: 'app config app'