/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eureka.servicesupplier.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;

@SpringBootApplication
@EnableDiscoveryClient
public class ServiceSupplier {
    public static void main(String[] args) {
        SpringApplication.run(ServiceSupplier.class, args);
    }
}
