
spring:
  profiles:
    active: 'prod'
  application:
    name: 'demo application'
  #main:
    #web-application-type: none
  cloud:
    config:
      server:
        git:
          uri: "file:D:/IDEA/java/springdemo/configuration/app-config/"
      uri: 'http://localhost:8080'
      name: configdemo

server:
  servlet:
    context-parameters:
      scp: 'scpV'
  port: 8080
logging:
  level:
    org.springframework.boot:
      trace
app:
  meta:
    version: 2
    sub-version: 2