spring:
  profiles:
    active: 'prod'
  application:
    name: 'demo application'
  main:
    web-application-type: none
server:
  servlet:
    context-parameters:
      scp: 'scpV'
logging:
  level:
    org.springframework.boot:
      trace
app:
  meta:
    version: 2
    sub-version: 2